### ISSUE TITLE
您好，想请教下如何在N1上安装nixos的

### ISSUE THREAD

**Issue by AaronYES** [cattyhouse/new-uboot-for-N1#2]
我 [在这里看到的这个项目](https://github.com/nix-community/nur-combined/blob/master/repos/slaier/modules/extlinux/uboot-phicomm-n1/package.nix#L23C17-L23C63) ，自己折腾了一阵子，可惜一直没有成功

**Comment by cattyhouse** [comment]
不好意思, 我对 NixOS不熟悉, 没有装过.

**Comment by AaronYES** [comment]
好吧，谢谢啦
