### ISSUE TITLE
询问uboot来源

### ISSUE THREAD

**Issue by SuzukiHonoka** [cattyhouse/new-uboot-for-N1#3]
你好，我一直是n1内核的维护者，见我的s905d-kernel-precompile仓库。
我编译的内核都需要更改内核text_offset参数，有了这个uboot可以直接编译，所以想请教一下uboot的来源，非常感谢！

**Comment by cattyhouse** [comment]
就是官网uboot然后用相似的某个profile编译


Regards
Justin He

**Comment by cattyhouse** [comment]
make libretech-cc_defconfig


Regards
Justin He

**Comment by SuzukiHonoka** [comment]
感谢回复，请问是这个吗？
https://github.com/libre-computer-project/libretech-u-boot/blob/master/configs/libretech-cc_v2_defconfig

**Comment by cattyhouse** [comment]
https://github.com/u-boot/u-boot

**Comment by SuzukiHonoka** [comment]
感谢回复
